apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-label
  template:
    metadata:
      labels:
        app: nodejs-label
    spec:
      containers:
      - name: nodejs-service
        image: ndarshan884/nodejs:1.0.2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-label
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
