---
apiVersion: v1
kind: Service
metadata:
  name: "hello-nodejs"
  namespace: "default"
spec:
  type: NodePort
  ports:
  - name: "port-8080"
    port: 8080
  selector:
    appname: "hello-nodejs"
    version: "{{BUILD_NUMBER}}"
